baseURL = 'https://blog.jelly.science/'
languageCode = 'en-us'
title = 'infiniflux'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
identifier = "links"
name = "Links" 
url = "/links/"
weight = 10